### ISSUE TITLE
invite link doesn't have correct permissions

### ISSUE THREAD

**Issue by zeratax** [GreepTheSheep/discord-trackmania.io#39]
apparently the bot now only supports slash commands and wasn't doing anything on my server anymore, since it didn't join with the correct permissions.
i had to reinivite it with a modified invite link, which includes `scope=applications.commands`
here the full invite link i used to make the bot work again:
`https://discord.com/oauth2/authorize?client_id=810191349214871583&scope=applications.commands%20bot&permissions=604367952`

**Comment by GreepTheSheep** [comment]
👋 hey @zeratax, where did you took this invite?

**Comment by zeratax** [comment]
ah sorry ^^ from the readme:
https://github.com/GreepTheSheep/discord-trackmania.io/commit/b5a395bc57dcdf2e0338c05abfd8bcc6a9436d78#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R4

**Comment by GreepTheSheep** [comment]
ah yeah, haven't updated that one. I'll make that change, thanks!
